### ISSUE TITLE
CSS3-UI Editor's draft updated with self-review answers to questionnaire

### ISSUE THREAD

**Issue by tantek** [w3ctag/security-questionnaire#1]
http://dev.w3.org/csswg/css-ui-3/#security-privacy-considerations

Please review and see if this is roughly what was intended/expected as self-review answers.

CSSWG just resolved to publish an updated TR WD with this appendix, so it'll be on TR "soon" (by next Tuesday maybe?).

**Comment by diracdeltas** [comment]
This looks good to me! cc @mikewest in case he wants to do a re-review.
