### ISSUE TITLE
Low level system access

### ISSUE THREAD

**Issue by jonathanKingston** [w3ctag/security-questionnaire#10]
Raising this as a place holder as it might be covered by:

3.9 - Does this specification allow an origin access to aspects of a user’s local computing environment?

As use high performance timing, low level memory and CPU access poses it's own risks it might be worth mentioning as part of this questions notes.

**Comment by mnot** [comment]
Good point - this should at least be called out.

**Comment by jonathanKingston** [comment]
The UDP specification mentioned in this call for review is a good example of something like this:
http://www.w3.org/blog/news/archives/4746?pk_campaign=feed&pk_kwd=call-for-review-proposal-to-relicense-unfinished-sysapps-specification-tcp-and-udp-socket-api

The specification itself has a TODO issue for security considerations.
