### ISSUE TITLE
use automatic publishing

### ISSUE THREAD

**Issue by samuelweiler** [w3ctag/security-questionnaire#101]
Can we arrange for this doc to be automatically published, so we don't need to point at the editor's drafts?

If we need help, PLH is likely willing to help.

**Comment by torgo** [comment]
Looping in @ylafon…

**Comment by samuelweiler** [comment]
At the least, can we do another versioned release in the next week or so?

**Comment by hober** [comment]
Sounds good to me. I've never done this before, so I don't know where to start.

**Comment by ylafon** [comment]
There are manual steps when publishing as the (c) section is not the usual one, so it would require some adaptation in order to do automatic publishing.

**Comment by samuelweiler** [comment]
(c) section?

**Comment by samuelweiler** [comment]
Any update on this?  I dislike that the published version is so very much out of date...

**Comment by ylafon** [comment]
There are roadblocks that we are working on, expect this to use automatic publishing once the issues in getting design-principles document  to do the same will be solved.

**Comment by pes10k** [comment]
Publishing a snapshot sounds good to me!

**Comment by torgo** [comment]
Hi @ylafon any update on this? I think we are all keen to set up a process via which this can be auto-published.

**Comment by torgo** [comment]
Just to be clear - auto-publication would imply that joint agreement is reached between PING and TAG via the PR and PR approval mechanism. And therefore any merged PR is a-ok to auto-publish to TR space.

**Comment by wseltzer** [comment]
I understand there's a Process issue. In the meantime, could we mint a new snapshot?

**Comment by hober** [comment]
@wseltzer wrote, in February:

> I understand there's a Process issue. In the meantime, could we mint a new snapshot?

A [new snapshot](https://www.w3.org/TR/security-privacy-questionnaire/) got published in March.

Leaving this open as we still don't have automatic publishing set up for this document.

**Comment by samuelweiler** [comment]
Tickling this issue, since people file new issues (like https://github.com/w3ctag/security-questionnaire/issues/129) that are already fixed in the editor's draft.

**Comment by ylafon** [comment]
It should be part of implementation of process 2021 in specberus, so no progress can be made until the tool allow it.

**Comment by hober** [comment]
> It should be part of implementation of process 2021 in specberus, so no progress can be made until the tool allow it.

I *think* those updates have happened, but I'm not sure. What say you, @ylafon?

**Comment by hober** [comment]
Any updates here, @ylafon @samuelweiler? We'd love to not have to think too hard about when to publish this thing.

**Comment by ylafon** [comment]
It is making (slow) progress, I should be able to test soon, if it works, then we can make it automatic.
