### ISSUE TITLE
Add a section for preventing behaviours that are abusive toward users

### ISSUE THREAD

**Issue by hadleybeeman** [w3ctag/security-questionnaire#106]
At our virtual W3CTAG face-to-face, we reviewed a [related issue](https://github.com/w3ctag/ethical-web-principles/issues/25) on the [Ethical Web Principles](https://www.w3.org/2001/tag/doc/ethical-web-principles/).

We concluded that dark patterns are, in fact, a subset of abusive practices. We spend a lot of energy brainstorming abusive practices when we are doing design reviews, and we think it would be good for the web community if spec authors did something similar (before their work came to us).

The [Security and Privacy Self Questionnaire](https://w3ctag.github.io/security-questionnaire/) is our current mechanism to prompt spec authors to think through what might go wrong.

Our abuse scenarios weren't specifically security or privacy related: for example, if a site asks you to "click okay to prove you're not a robot", and your "Okay" actually grants permission for push notifications (without your knowledge) — that is an abusive behaviour, but not compromising your security or privacy.

We agreed that we would find a way to add the topic into the Questionnaire. This issue is to kick that off.

**Comment by hober** [comment]
Can we address this by updating our design review issue template?

**Comment by hober** [comment]
Or maybe this belongs in the Societal Impact Questionnaire?

**Comment by hober** [comment]
Note to self: we should be able to close this issue with a PR that links to the new Privacy Principles and/or Societal Impact Questionnaire.
