### ISSUE TITLE
Supply chains can be trusted – with evidence

### ISSUE THREAD

**Issue by jwrosewell** [w3ctag/security-questionnaire#112]
Nearly all website operators use services provided by suppliers to operate their business and provide web access to end users. These website operators are not forced to use particular suppliers but benefit from a competitive open market to select from. They enter into commercial contracts with these suppliers. It is therefore reasonable to assume that they trust these suppliers to adhere to the relevant laws and the contract they have entered into. Should the TAG wish, I can provide evidence that websites make use of such suppliers by reference to a myriad of documents and materials from such providers.

The document needs to be amended to support this reality and the choices website operators must have.

**Comment by plinss** [comment]
Closed as a duplicate of #83

This new issues brings no new information, and despite the title, adds no evidence.
