### ISSUE TITLE
The current questionnaire is very browser-centric

### ISSUE THREAD

**Issue by atanassov** [w3ctag/security-questionnaire#116]
The examples, questions and overall content in the current version are mostly browser oriented. This makes the barrier for entry very high for anyone coming to it from the non-browser world. 

Consider adding an entry level split that guides users to browser vs non-browser scenarios, features and/or users of the doc.

**Comment by dauwhe** [comment]
I'm just starting these questions for EPUB 3.3, and am facing exactly this problem. How do I reason about security when HTML content is being presented in a web view in an Android app, after I paid for the content with my credit card information?

**Comment by hober** [comment]
Hi all,

@pes10k, @plinss, and I talked about this today in our San Diego F2F. I wonder if we could do something similar to the HTML spec's web developer edition. That is, could have some kind of toggle at the top of the questionnaire like "does your spec/feature/whatever rely on the same-origin policy / the web's fundamental privacy and security model?" If no, we `display: none` a bunch of questions that are apparently irrelevant, and maybe `display: block` an additional question or two along the lines of "if you're thing isn't built on the web's privacy and security model, what is the privacy and security model it's built on?"

**Comment by pes10k** [comment]
this seems stale, though if folks are still interested please reopen or create a new issue
