### ISSUE TITLE
Mention (capability) negotiation?

### ISSUE THREAD

**Issue by samuelweiler** [w3ctag/security-questionnaire#122]
Capability negotiation is a fraught area.  Should we say something about it using those words?  (Our general words aren't wrong, but perhaps calling this out might help people to spot it?)

**Comment by hober** [comment]
Note to self: text should maybe reference https://www.w3.org/DesignIssues/Conneg (though that document should be re-evaluated; is it something we can agree with in this day and age?)

**Comment by hober** [comment]
I think this might be a refactoring task more than anything. Several existing questions cover this area, but you wouldn't find the relevant text by searching for "negotiation" in the document.

**Comment by hober** [comment]
Closing as the document already covers this area, though it's a fair point that discoverability of that could be improved.
