### ISSUE TITLE
Do we need something about noise?

### ISSUE THREAD

**Issue by torgo** [w3ctag/security-questionnaire#154]
https://github.com/w3ctag/privacy-principles/issues/261

**Comment by hober** [comment]
Could you take a look at this one, @pes10k?

**Comment by pes10k** [comment]
I think we can close this out, in favor of the concern here https://github.com/w3ctag/ethical-web-principles/issues/94#issuecomment-1661896067

I can try and incorporate the concern that drove https://github.com/w3ctag/privacy-principles/issues/261 into new text for the above though
