### ISSUE TITLE
Ask about dependencies and maturity of dependencies

### ISSUE THREAD

**Issue by rhiaro** [w3ctag/security-questionnaire#155]
Feedback on the questionnaire [in response from VCWG](https://github.com/w3c/vc-status-list-2021/issues/77):

> The questionnaire should focus more on the dependencies of the specification in question, the maturity level of those dependencies and if they have received any security analysis or review, it was more concerned with the browser security context rather than the general web security model.

Related: #116

**Comment by pes10k** [comment]
Discussed. We think this is beyond the scope of the document. It may be a better fit for other documents like design principals. If you still have this concern, we suggest opening an issue on that document
