### ISSUE TITLE
How do we get additional review with the wider w3c community?

### ISSUE THREAD

**Issue by torgo** [w3ctag/security-questionnaire#16]
As discussed in AB meeting 29 October 2015 at TAPAC.

**Comment by tantek** [comment]
This may be something that the AB can help with, since it is somewhat process related, across W3C (rather than specific to any particular WG). Please feel free to make specific requests if you have suggestions for how we can help :)

**Comment by mnot** [comment]
We've had a few discussions about how we want to position this kind of document, and I think our position is that we *don't* want to force this on people -- i.e., we don't want to create more process hoops. 

Publicising it is a different matter, of course.

**Comment by tobie** [comment]
It would be extremely useful to have a blueprint or the privacy and security consideration section of specs. I could even imagine a basic one -page app, that asked you the different questions found in the questionnaire and that built an outline for you with placeholders for content to fill-in.

Nothing drives adoption of best practices more than tools that simplify people's job and happen to do things the right way.
