### ISSUE TITLE
Provide an example of a good "Security Considerations" and "Privacy Considerations" section

### ISSUE THREAD

**Issue by patrickhlauke** [w3ctag/security-questionnaire#25]
It would be helpful if 3.16 gave an actual (non-normative) example of what a good security/privacy considerations section could look like in the context of an actual specification document.

(xref my very naive attempt https://github.com/w3c/pointerevents/pull/193 prompted by a recent ReSpec warning - if the spec here provided an example, I would have probably understood better what this entailed)

**Comment by marcoscaceres** [comment]
You are kinda missing the point tho. The questionnaire provides examples and forces the editors to reflect deeply on the implications of their API. You should not seek a copy/paste solution from another spec here: just get a cup of coffee, print out the question, and go through them. I promise you it's totally worth while - and super enlightening. If the questionnaire is ambiguous or confusing, then that's something we should take up with @mikewest. I'm sure he is happy to help or clarify anything that doesn't make sense. 

Regarding dropping the bullets, that's fine: just *make sure you've thought about each before removing them*.

**Comment by patrickhlauke** [comment]
I'm not asking for a copy/paste solution. Just literally "here's an example of what shape/form this could take in a real-world context", as it's all a bit abstract otherwise.
