### ISSUE TITLE
gh-pages branch out of sync with master

### ISSUE THREAD

**Issue by wseltzer** [w3ctag/security-questionnaire#28]
Is the gh-pages branch serving a purpose here? 

What's displayed at https://w3ctag.github.io/security-questionnaire/
appears to be older than master (i.e. https://rawgit.com/w3ctag/security-questionnaire/master/index.html )

Thanks, working with PING folks to coalesce the various documents here!

**Comment by dbaron** [comment]
I changed the settings to display the `master` branch (currently 61520b7d65ebf0404097a82164add05e7fdf83f1) rather than the `gh-pages` branch (currently 1f854b0a6f57d70596e1a3e0c1c81a5c086d5eab).

**Comment by dbaron** [comment]
And I've now deleted the `gh-pages` branch to avoid future confusion.  (Everything on `gh-pages` was on `master`... `master` was just 7 commits ahead.)
