### ISSUE TITLE
script (execution/loading) OR (script execution)/(loading) mechanisms

### ISSUE THREAD

**Issue by tantek** [w3ctag/security-questionnaire#3]
This question: "Does this specification enable new script execution/loading mechanisms?" is ambiguous and should be clarified.

I interpreted it broadly, as one should in the context of ambiguity in security, as (script execution)/(loading) mechanisms, especially since there were no other questions about "loading" of arbitrary (not just script) resources, which has network effects, tracking, etc.

For reference: http://dev.w3.org/csswg/css-ui-3/#security-privacy-considerations

**Comment by diracdeltas** [comment]
I agree with @tantek's interpretation in http://dev.w3.org/csswg/css-ui-3/#security-privacy-considerations
