### ISSUE TITLE
Introduction section needs to be more friendly

### ISSUE THREAD

**Issue by torgo** [w3ctag/security-questionnaire#46]
This document's introduction section is too long, contains overly complex wording for things that should be simple and straightforward and in some cases contains misleading advice. For example, the paragraph on how to interact with PING, should arguably be removed as we don't want every group to talk to ping first.

**Comment by lknik** [comment]
Thanks for the feedback. Can you provide example of overly complex wording in section 1?

**Comment by lknik** [comment]
Xth attempt at this, now with improved colour: https://github.com/w3ctag/security-questionnaire/pull/50
