### ISSUE TITLE
[Meta] There should only be one issue tracker

### ISSUE THREAD

**Issue by hober** [w3ctag/security-questionnaire#47]
(With my TAG hat on)

We noticed today that there are two issue trackers associated with this document, a [w3cping one](https://github.com/w3cping/security-questionnaire/issues) and a [w3ctag one](https://github.com/w3ctag/security-questionnaire/issues). This is confusing, and resulted in different TAG members filing issues in different places today. The questionnaire itself links to both of these (one under "Issue Tracking" and one under "Bug Reports."

We acknowledge that this document is a joint work item, and we're not picky about which issue tracker gets used. But please just use one, and please remove the redundant link from the document's front matter.

**Comment by hober** [comment]
See also https://github.com/w3cping/security-questionnaire/issues/21

**Comment by lknik** [comment]
Thanks. We retained it separate when editing the document initially. I believe now everything should be issued here, as we have the old document already updated.

**Comment by samuelweiler** [comment]
The redundant link to Jason's repo (under the "Issue Tracking" label) still needs to be removed.
