### ISSUE TITLE
Need a "How to Use This Questionnaire" section

### ISSUE THREAD

**Issue by mnot** [w3ctag/security-questionnaire#5]
Somewhere near the intro we need to give people more solid guidance about how to use this specification. 

Suggestion below.
## How to Use This Questionnaire

To be most effective, the questions below should be considered early in the specification development process, and kept in mind as it matures. Applying this questionnaire as a "check box" step before requesting final publication doesn't help improve privacy or security on the Web.

It's not necessary to include the questionnaire in the specification itself; for example, it might be preferable to keep it in a wiki and put a temporary link to that in the specification. Likewise, the entire questionnaire need not be repeated question-for-question when filled out; what's important is that each question is considered and that any privacy or security concerns are appropriately dealt with.

When you discover privacy and security concerns, there are many ways of dealing with them. Strategies for handling them are discussed in [ref], and ought to be discussed with other parties such as the TAG to assure a consistent approach throughout the Web; we already have a number of mismatches between capabilities and approaches across the platform as individual groups have taking a one-off approach to dealing with such concerns.

**Comment by dontcallmedom** [comment]
FWIW, there was push back in the WebRTC WG about putting the results of this questionnaire as is in the spec; adding some more information as to what to do with the collected answers in the questionnaire or in an accompanying document would help.

**Comment by hober** [comment]
The document already has a [How To Use The Questionnaire](https://w3ctag.github.io/security-questionnaire/#howtouse) section. I wonder why I reopened this in December? `¯\_(ツ)_/¯`
