### ISSUE TITLE
"editor's draft" stylesheet or cue?

### ISSUE THREAD

**Issue by koalie** [w3ctag/security-questionnaire#54]
Procedural comment:

I think it would be less confusing if the editor's draft https://w3ctag.github.io/security-questionnaire/ bore an "editor's draft" cue, stylesheet or visual indication.

When we start from the published note https://www.w3.org/TR/2015/NOTE-security-privacy-questionnaire-20151210/ it's not obvious which is the latest document and what status it's in.

Thanks!

**Comment by lknik** [comment]
Done.
