### ISSUE TITLE
Publish this at a versioned URL

### ISSUE THREAD

**Issue by diracdeltas** [w3ctag/security-questionnaire#6]
Related to #1, Tantek mentioned it would be helpful to for specs to reference specific versions of this document.

**Comment by diracdeltas** [comment]
@plinss can this be done on the W3C site?

**Comment by plinss** [comment]
Sure, it just depends on where you want to publish it. We can publish under w3.org/TR/ as a NOTE, somewhere under http://www.w3.org/2001/tag/doc/ as a TAG finding, or somewhere under tag.w3.org however we want. 

It somewhat depends on what kind of document we expect this to be, how often we expect to update it, and how specs will refer to it. I'm currently thinking it might work best as a NOTE under w3.org/TR/ (url permanence, automatic versioning, better for normative references, etc)

**Comment by diracdeltas** [comment]
I'm fine with w3.org/TR. @tantek any thoughts?

**Comment by mikewest** [comment]
Publishing as a note sounds totally reasonable to me. I suspect that we'll end up with a few iterations on the document in the first months, and then we'll have a period of stability until we invent totally new ways of creating insecurity. I wouldn't expect frequent updates in the long term.

**Comment by tantek** [comment]
A NOTE under w3.org/TR/ would be great, publish early publish often. Assuming no one has any strong objections to the current github draft, it would be great if the TAG could go ahead and publish it as a NOTE ASAP. Then I'll update CSS3-UI (which we're hoping to publish as a CR soon) to cite that dated permalink for the questionnaire. Thanks!

**Comment by tantek** [comment]
Update on this? 

A note would be great ASAP so we can reference that in the CSS3-UI CR draft coming up. Thanks!

**Comment by plinss** [comment]
The TAG resolved to publish as a note, but we want to add a "status of this document" section first. diracdeltas was "volunteered" to write it. Happy to revisit/reassign if you can't get to it.

**Comment by torgo** [comment]
@ylafon to put into action

**Comment by diracdeltas** [comment]
Sounds like this should be a TAG finding? Unfortunately the boilerplate for that doesn't include the "status of this document" yet, c.f. https://github.com/tabatkins/bikeshed/issues/407. I'm happy to open a pull request anyone if people are fine without a status section.

**Comment by diracdeltas** [comment]
Per the meeting today, apparently this is going to be a formal note.

**Comment by plinss** [comment]
Published at https://www.w3.org/TR/security-privacy-questionnaire/ on 2015-12-10
