### ISSUE TITLE
Geofencing link is not helpful

### ISSUE THREAD

**Issue by vasilvv** [w3ctag/security-questionnaire#61]
It's supposed to be used an example of how to do something with an API, but the linked explainer looks like it was never finished before it was abandoned.

**Comment by torgo** [comment]
We discussed on the call today. The consensus was to keep it (as it's just an example) unless there is a more relevant and current example that could be used in its place? To be clear, this is referencing [section 2.4](https://w3ctag.github.io/security-questionnaire/#sensitive-data).

**Comment by tomayac** [comment]
There is a (likewise abandoned) spec, which may at least be the better link target: https://www.w3.org/TR/geofencing/.

**Comment by torgo** [comment]
Thanks for that inout, Thomas. We discussed this in the our [virtual f2f](https://github.com/w3ctag/meetings/blob/gh-pages/2020/05-distributed/README.md) and decided to keep it the way it is.
