### ISSUE TITLE
Unclear which repository issues should be filed in.

### ISSUE THREAD

**Issue by mkruisselbrink** [w3ctag/security-questionnaire#62]
The "issue tracking" link in https://w3ctag.github.io/security-questionnaire/ links to https://github.com/w3cping/security-questionnaire/issues/, so that is where I went to file https://github.com/w3cping/security-questionnaire/pull/25. There is nothing on that page that makes it seem like that is the wrong place. However on https://github.com/w3cping/security-questionnaire it does say "Please file issues in the w3ctag repository, not here!". So where should issues actually be filed?

(I'm now noticing that https://w3ctag.github.io/security-questionnaire/ actually has links to both issue trackers, one labelled "Issue Tracking" and one labeled "Bug Reports".

**Comment by hober** [comment]
I think this is a duplicate of #47, which appears to have been closed in error.

**Comment by lknik** [comment]
Thanks a lot. Indeed please submit in TAG repository. Done.

**Comment by mkruisselbrink** [comment]
You don't seem to have actually regenerated the HTML, only the bikeshed source? So https://w3ctag.github.io/security-questionnaire/ still has both links. Also probably the reason that the "Issue Tracking" link there is wrong in the first place is that whoever last generated the html had a checkout from the ping fork, leading bikeshed to assume that is the github repository, since the bikeshed metadata doesn't explicitly specify a repository.

**Comment by hober** [comment]
Reopening. I don't understand why this issue (and #47) got closed when there is still a link to https://github.com/w3cping/security-questionnaire/issues/ in the document at https://w3ctag.github.io/security-questionnaire/

**Comment by lknik** [comment]
Ok.

Though actually the main document seems OK: https://www.w3.org/TR/security-privacy-questionnaire/

**Comment by mkruisselbrink** [comment]
Yes, because as said the bikeshed source doesn't specify the repository to use, so it completely depends on where whoever generates the html checked out from what issue tracker the html will link to. That combined with not having automated builds of editors drafts means that it is completely arbitrary what repository will be used. To fix this you should add Repository: metadata to the bikeshed source.

**Comment by lknik** [comment]
Thanks. In the meantime regenerated it (in a haste).

**Comment by lknik** [comment]
Repository added here https://github.com/w3ctag/security-questionnaire/pull/67

**Comment by lknik** [comment]
Thanks.
