### ISSUE TITLE
Cite the source of the "concrete privacy concerns"

### ISSUE THREAD

**Issue by jyasskin** [w3ctag/security-questionnaire#71]
The "privacy concerns" in https://w3ctag.github.io/security-questionnaire/#threats look like they were copied from https://tools.ietf.org/html/rfc6973#section-5, but that use isn't cited. In addition to being polite, referencing RFC 6973 (or another original source for this list) would help me find more explanation if the single-sentence summaries here aren't sufficient.

**Comment by lknik** [comment]
Hi,

This model (the threats) is fairly broadly used. But I'm OK for referencing anyhow.
 @mikewest, do you recall how this got in there?
(ot blaming anyone ;-) )

**Comment by hober** [comment]
@jyasskin, is PR #73 sufficient to address this?

**Comment by hober** [comment]
Please take a look, @pes10k.
