### ISSUE TITLE
Explain how groups should address issues raised by the questionnaire in their specs

### ISSUE THREAD

**Issue by pes10k** [w3ctag/security-questionnaire#88]
Re: https://github.com/w3ctag/security-questionnaire/pull/87#pullrequestreview-427656221

Should add discussion that sec + priv issues should be solved by the specs, not just pointed at.

**Comment by torgo** [comment]
I agreed today to draft some text that could help do this.

**Comment by pes10k** [comment]
Howdy @torgo, just checking if you had text for this.  If not, would you mind if i take a go at it?

**Comment by hober** [comment]
@torgo, have you found any time for this recently?

**Comment by pes10k** [comment]
@torgo just a nudge, we're hoping to close out as many open issues as possible.  If you could take a look that'd be appreciated

**Comment by pes10k** [comment]
actually @torgo we decided to close this out.  Apologies for having this on your TODO plate for 2 years ;)
