### ISSUE TITLE
Consider merging or retitling questions 2.1 and 2.8

### ISSUE THREAD

**Issue by hober** [w3ctag/security-questionnaire#97]
By title, they appear to be exactly the same. By content, 2.8 is more about exposing data across origins, whereas 2.1 is about exposing data at all.

It may be reasonable to merge the two questions, or maybe we should simply retitle them so the difference is clearer. Personally, I'm leaning toward merging them.

@pes10k thoughts?

**Comment by pes10k** [comment]
@hober i think thats a great idea.  I vote for collapsing 2.8 into 2.1, and just mentioning in the body of the new 2.1 to specify:

1. what info is newly available to 1ps
2. what info is newly available to 3ps
3. what currently available info is mirrored (1p and / or 3p)

If that sounds good, and if you dont already have a PR for me to build from, i'd be happy to put a PR together!

**Comment by hober** [comment]
@pes10k wrote:

> If that sounds good,

It does.

> and if you dont already have a PR for me to build from,

I don't.

> I'd be happy to put a PR together!

That'd be great!

**Comment by pes10k** [comment]
re convo with @samuelweiler, will instead see if we can remove both 2.1 and 2.8 and instead move them into intro text

**Comment by pes10k** [comment]
closed by https://github.com/w3ctag/security-questionnaire/pull/100
